let mensagens = [
    "A vida é uma jornada, não um destino",
    "A esperança é a luz no fim do túnel",
    "A gentileza transforma o mundo",
    "Aprenda com ontem, viva para hoje, sonhe com amanhã",
    "O amor é a linguagem universal",
    "A persistência leva ao sucesso",
    "A simplicidade é a sofisticação final",
    "A coragem é a chave para a liberdade",
    "Seja a mudança que você deseja ver no mundo",
    "O sorriso é o melhor remédio",
    "O tempo é o recurso mais valioso",
    "A gratidão transforma o que temos em suficiente",
    "O conhecimento é poder",
    "A verdade liberta",
    "O respeito é mútuo",
    "A humildade é a chave para o crescimento",
    "A fé move montanhas",
    "A criatividade é a inteligência se divertindo",
    "A paciência é uma virtude",
    "A alegria está no caminho, não no destino",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia",
    "A compaixão cura",
    "A vida começa no final da sua zona de conforto",
    "Onde há vontade, há um caminho",
    "A mente é tudo, você se torna o que você pensa",
    "A inspiração está ao seu redor, encontre-a",
    "A jornada de mil milhas começa com um único passo",
    "A vida é um livro, escreva uma boa história",
    "A resiliência é a chave para superar desafios",
    "A alegria compartilhada é uma alegria redobrada",
    "A coragem é a escada para o sucesso",
    "A verdadeira felicidade vem de dentro",
    "A bondade é a luz que guia",
    "A esperança é o amanhecer após a escuridão",
    "A ação é a base do sucesso",
    "A gratidão transforma obstáculos em oportunidades",
    "A mente tranquila traz força interior",
    "A vida é um espelho, reflita bondade",
    "A simplicidade é a essência da elegância",
    "A paciência constrói caráter",
    "A determinação é a faísca do progresso",
    "A fé é o vento nas asas da esperança",
    "A criatividade é o coração da inovação",
    "A verdade sempre prevalece",
    "A compaixão é a essência da humanidade",
    "A felicidade é um estado de espírito",
    "A mudança começa com você",
    "A perseverança é o segredo dos grandes realizadores",
    "A paz de espírito é a maior riqueza",
    "A vida é uma dança, aproveite cada passo,",
    "A verdadeira felicidade está em aproveitar o presente sem ansiedade",
    "A sabedoria começa na admiração",
    "Cada dia é uma nova oportunidade para ser melhor",
    "A liberdade é o oxigênio da alma",
    "A bondade é o começo de tudo",
    "O otimismo é a fé em ação",
    "A honestidade é o primeiro capítulo no livro da sabedoria",
    "A ação é a chave fundamental para todo sucesso",
    "A beleza da vida está nos pequenos detalhes",
    "A mudança é a única constante na vida",
    "O fracasso é apenas a oportunidade de começar de novo com mais experiência",
    "A integridade é fazer a coisa certa, mesmo quando ninguém está olhando",
    "A confiança é o cimento que mantém a vida juntos",
    "A inspiração vem dos outros, a motivação vem de dentro de nós",
    "A felicidade não é algo pronto, ela vem das suas próprias ações",
    "A vida é sobre criar e viver experiências que valham a pena",
    "A verdadeira riqueza está na saúde, não no ouro e na prata",
    "A paz interior começa no momento em que você escolhe não permitir que outra pessoa ou evento controle suas emoções",
    "A simplicidade voluntária é um caminho para a felicidade",
    "A curiosidade é a faísca do aprendizado",
    "A serenidade vem quando trocamos expectativas por aceitação",
    "A verdadeira força vem de superar o que você pensou que não podia",
    "A confiança é a base de qualquer relacionamento saudável",
    "A gentileza é a linguagem que os surdos podem ouvir e os cegos podem ver",
    "A vida é curta demais para esperar",
    "A vida é uma arte, aproveite cada momento",
    "A imaginação é o começo da criação",
    "A empatia constrói pontes entre corações",
    "A liberdade verdadeira é ser você mesmo",
    "A vida floresce com gratidão",
    "A simplicidade revela a verdadeira beleza",
    "A perseverança vence a resistência",
    "A felicidade é uma jornada, não um destino",
    "A humildade é a verdadeira sabedoria",
    "A honestidade é o melhor caminho",
    "A paixão é o combustível do sucesso",
    "A coragem nasce do coração",
    "A determinação transforma sonhos em realidade",
    "A fé é acreditar no invisível",
    "A paciência é a mãe de todas as virtudes",
    "A vida é um presente, valorize-a",
    "A alegria é contagiante, espalhe-a",
    "A paz começa com um sorriso",
    "A verdadeira amizade é um tesouro",
    "A bondade retorna a quem a pratica",
    "A esperança é a bússola da alma",
    "A verdadeira beleza vem de dentro",
    "A compaixão enriquece o espírito",
    "A mente aberta é uma mente livre",
    "A verdade é a base de todas as virtudes",
]

let btn = document.querySelector("button");
let btnLimpar = document.querySelector("#clearButton");
let mensagem = document.querySelector("p");

btn.addEventListener("click", () => {
    let randon = Math.floor(Math.random() * mensagens.length);
    mensagem.textContent = mensagens[randon]
})

btnLimpar.addEventListener("click", () => {
    mensagem.textContent = "";
});